### ISSUE TITLE
Invalid renovate config?

### ISSUE THREAD

**Issue by okainov** [nicholasdille/renovate-homebrew#250]
I was looking around for renovate usages and I found out you use `extractVersion` with `major/minor/patch` here https://github.com/nicholasdille/renovate-homebrew/blob/b0605df2d864cbdd78bd4192cf21dd41c948a49d/renovate.json#L62, but it seems to be wrong renovate config, `extractVersion` seems to support only `version` inside.

**Comment by nicholasdille** [comment]
@okainov Thanks for your hint! This pointed me in the correct direction :-)

**Comment by nicholasdille** [comment]
All fixed
